import { ThemeProvider } from "@/src/core/theme"
import { cn } from "@/src/shared/utils/utils"
import { Header } from "@/src/widgets/header"
import type { Metadata } from "next"
import { Geist, Geist_Mono, Inter } from "next/font/google"
import { Suspense } from "react"
import { TodoProvider } from "./(providers)/todo.provider"
import "./globals.css"

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: {
    template: "%s | TodoList",
    default: "TodoList",
  },
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable
      )}
      suppressHydrationWarning
    >
      <body className="flex min-h-full flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
          enableSystem
        >
          <Suspense fallback={null}>
            <TodoProvider>
              <Header />
              <main className="flex-1 bg-neutral-100 dark:bg-neutral-900">
                {children}
              </main>
            </TodoProvider>
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  )
}
